// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// isoreg_Best_1990_cpp
NumericVector isoreg_Best_1990_cpp(NumericVector y);
RcppExport SEXP Best1990_isoreg_Best_1990_cpp(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(isoreg_Best_1990_cpp(y));
    return rcpp_result_gen;
END_RCPP
}
