# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Isotonic regession after Best & Chakravarti (1990)
#'
#' C++ implementation of Algorithm A from Best & Chakravarti (1990).
#' Performs iso tonic regression with a runtime complexity of \eqn{\mathcal{O}(n)}
#'
#' Best, M.J. & Chakravarti, N. Mathematical Programming (1990) 47: 425.
#' \href{http://doi.org/10.1007/BF01580873}{doi:10.1007/BF01580873}
#'
#' @useDynLib Best1990
#' @importFrom Rcpp evalCpp
#' @param y target values.
#' @return fitted values.
#' @examples
#' y <- c(1, 3, 2, 4)
#' isoreg_Best_1990_cpp(y)
#' @export
isoreg_Best_1990_cpp <- function(y) {
    .Call('Best1990_isoreg_Best_1990_cpp', PACKAGE = 'Best1990', y)
}

