# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Isotonic regession after Best & Chakravarti (1990)
#'
#' C++ implementation of Algorithm A from Best & Chakravarti (1990).
#' Performs iso tonic regression with a runtime complexity of \eqn{\mathcal{O}(n)}
#'
#' Best, M.J. & Chakravarti, N. Mathematical Programming (1990) 47: 425.
#' \href{http://doi.org/10.1007/BF01580873}{doi:10.1007/BF01580873}
#'
#' @useDynLib isoregr
#' @importFrom Rcpp evalCpp
#' @param y target values.
#' @return fitted values.
#' @author Jan Gleixner
#' @examples
#' y <- c(1, 3, 2, 4)
#' isoreg_Best_1990_cpp(y)
#' @export
isoreg_Best_1990_cpp <- function(y) {
    .Call('_isoregr_isoreg_Best_1990_cpp', PACKAGE = 'isoregr', y)
}

#' Compute rank of Q in X
#'
#' @importFrom Rcpp evalCpp
#' @param X Matrix of target values
#' @param Q Matrix of query values
#' @param nsw integer to tune hybrid algorithm
#' @return vector of rank of each row of Q in X
#' @export
rank_in_cpp <- function(X, Q, nsw = 400L) {
    .Call('_isoregr_rank_in_cpp', PACKAGE = 'isoregr', X, Q, nsw)
}

